max_steps = 20

[model]
name = "Qwen/Qwen3-30B-A3B-Instruct-2507"
seq_len = 16384
attn = "flash_attention_4"
impl = "custom"

[model.lora]
rank = 16

[model.compile]

[model.ac]

[optim]
lr = 3e-5

[ckpt]
