max_steps = 100000

[model]
name = "PrimeIntellect/INTELLECT-3-SFT-Stage-2-v3-800"
impl = "custom"
load_using_meta = true

[model.ac]
freq = 1

[model.compile]

[optim]
type = "muon"
lr = 1e-6
weight-decay = 0.01

[loss]
mask_ratio_high = 5
mask_ratio_low = 0.5

[weights]
save_format = "safetensors"
save_sharded = true
interval = 30

[ckpt]
interval = 30
keep = 5

[wandb]
project = "intellect-3-rl"
name = "int3-train"

[log]
level = "debug"