trainer_gpu_ids = [0]
inference_gpu_ids = [1]

max_steps = 500

[wandb]
project = "math-group-debug"
name = "math-group"

[model]
name = "Qwen/Qwen3-4B-Instruct-2507"

[orchestrator]
max_inflight_groups = 48
rollouts_per_example = 16

[[orchestrator.env]]
id = "primeintellect/math-env"
name = "hendrycks-math"
args = { dataset_name = "PrimeIntellect/Hendrycks-Math", dataset_subset = "default" }

[[orchestrator.env]]
id = "primeintellect/math-env"
name = "acereason-math"
args = { dataset_name = "nvidia/AceReason-Math", dataset_subset = "default", question_key = "problem" }

[orchestrator.buffer]
easy_threshold = 1.0
hard_threshold = 0.0

[orchestrator.eval]
interval = 50

[[orchestrator.eval.env]]
id = "primeintellect/aime2024"
name = "aime2024"
num_examples = 30
rollouts_per_example = 4

[trainer.model]
seq_len = 4096

[inference.model]
max_model_len = 2048


