max_steps = 500
batch_size = 512
rollouts_per_example = 16
seq_len = 2048
mask_truncated_completions = false

[model]
name = "willcb/DeepSeek-R1-Distill-Qwen-1.5B"

[[env]]
id = "hendrycks-math"

[[env]]
id = "skywork-math"

[buffer]
type = "difficulty-pool"
hard_border = 0.0
easy_border = 0.9
easy_fraction = 0.0
hard_fraction = 0.0

[sampling]
max_tokens = 2048

[val]
num_examples = 8
rollouts_per_example = 8
interval = 5
 
[eval]
interval = 10

[[eval.env]]
id = "math500"
num_examples = 30

[[eval.env]]
id = "aime2025"