max_steps = 50
seq_len = 512

[wandb]
project = "multiagent-debug"
name = "rps"

[orchestrator.wandb.log_extras]
samples = true
interval = 10

[model]
name = "Qwen/Qwen3-1.7B"

[orchestrator]
batch_size = 128
rollouts_per_example = 16

[orchestrator.sampling]
max_tokens = 10
temperature = 1.5

[orchestrator.sampling.extra_body.chat_template_kwargs]
enable_thinking = false

[[orchestrator.env]]
id = "rock-paper-scissors"

[trainer]

[inference]
