[model]
name = "openai/gpt-oss-120b"

[sampling]
reasoning_effort = "high"
# reasoning_effort = "low"
temperature = 1.0

[sampling.extra_body.provider]
# order = ["fireworks"]
order = ["google-vertex"]
allow_fallbacks = false
