output_dir = "outputs/hendrycks-math"
max_steps = 500
seq_len = 2048

[slurm]
job_name = "hendrycks-math"

[deployment]
type = "multi_node"
num_train_nodes = 1
num_infer_nodes = 1

[log]
level = "debug"

[wandb]
project = "hendrycks-math-debug"
name = "hendrycks-math"

[model]
name = "Qwen/Qwen3-4B-Instruct-2507"

[orchestrator]
batch_size = 128
rollouts_per_example = 16

[orchestrator.sampling]
max_tokens = 2048

[[orchestrator.env]]
id = "math-env"
name = "hendrycks-math"
args = { dataset_name = "PrimeIntellect/Hendrycks-Math", dataset_subset = "default", math_verify_max_workers = 128, math_verify_timeout = 60 }

[orchestrator.buffer]
easy_threshold = 1.0
hard_threshold = 0.0

[trainer]

[inference.parallel]
dp = 8
