inference_gpu_ids = [0]
trainer_gpu_ids = [1]

max_steps = 100
seq_len = 4096

[model]
name = "Qwen/Qwen3-VL-4B-Instruct"

[ckpt]
interval = 50

[orchestrator]
batch_size = 128
rollouts_per_example = 16

[orchestrator.sampling]
max_tokens = 128

[[orchestrator.env]]
id = "text_to_image_simple"
name = "reverse-text-images-simple"
args = { base_env = "reverse-text", seed = 42, font_path = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", roles_to_image = ["user"] }

[orchestrator.val]
interval = 1
num_examples = 16

[trainer]

[trainer.model]
optimization_dtype = "bfloat16"
reduce_dtype = "bfloat16"

[trainer.optim]
lr = 3e-6

[inference]

[inference.parallel]
dp = 1
