inference_gpu_ids = [0]
trainer_gpu_ids = [1]

max_steps = 12
seq_len = 2048

[ckpt]
resume_step = 10

[model]
name = "PrimeIntellect/Qwen3-0.6B"

[trainer.optim]
lr = 1e-5

[orchestrator]
batch_size = 128
rollouts_per_example = 8

[orchestrator.sampling]
max_tokens = 384

[[orchestrator.env]]
id = "primeintellect/alphabet-sort"
name = "alphabet-sort"
args = { min_turns = 2, max_turns = 2, min_names_per_turn = 1, max_names_per_turn = 3, similarity_power = 4, power_per_turn = false }

[inference]
