max_steps = 30

[model]
name = "PrimeIntellect/Qwen3-0.6B-Reverse-Text-SFT"

[platform]
run_name = "Reverse Text"

[orchestrator]
rollouts_per_example = 16

[orchestrator.sampling]
max_tokens = 128

[orchestrator.prime_monitor]

[orchestrator.prime_monitor.log_extras]
interval = 5

[[orchestrator.env]]
id = "reverse-text"

[trainer.optim]
lr = 3e-6

[ckpt]

[inference]
