max_steps = 500
batch_size = 512
rollouts_per_example = 16
seq_len = 2048

[model]
name = "willcb/DeepSeek-R1-Distill-Qwen-1.5B"

[[env]]
id = "hendrycks-math"

[buffer]
type = "difficulty-pool"
hard_border = 0.0
easy_border = 0.9
easy_fraction = 0.0
hard_fraction = 0.0

[sampling]
max_tokens = 2048

[val]
num_examples = 16
rollouts_per_example = 8
interval = 1