inference_gpu_ids = [0]
trainer_gpu_ids = [1]
max_steps = 100

[model]
name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"

[orchestrator]
batch_size = 512
rollouts_per_example = 16
seq_len = 2048

[orchestrator.sampling]
max_tokens = 2048

[[orchestrator.env]]
id = "primeintellect/hendrycks-math"

[trainer]