max_steps = 20
seq_len = 2048

[model]
name = "PrimeIntellect/Qwen3-0.6B-Reverse-Text-SFT"

[wandb]
project = "reverse-text"
name = "reverse-text-eval"

[orchestrator]
batch_size = 128
rollouts_per_example = 16

[orchestrator.sampling]
max_tokens = 128

[[orchestrator.env]]
id = "reverse-text"

[orchestrator.eval]
interval = 5

[orchestrator.eval.sampling]
max_tokens = 128

[[orchestrator.eval.env]]
id = "reverse-text"
num_examples = 32
rollouts_per_example = 1

[trainer.optim]
lr = 3e-6

[ckpt]

[inference]
