max_steps = 30
batch_size = 512
rollouts_per_example = 16
max_async_level = 99
workers_per_env = 4

[model]
name = "Qwen/Qwen3-30B-A3B-Thinking-2507"

[sampling]
max_tokens = 512

# [[env]]
# id = "primeintellect/alphabet-sort"
# name = "alphabet-sort"
# args = { min_turns = 2, max_turns = 2 }

[[env]]
id = "mini-swe-agent-plus"
args = { max_turns = 50, cpu_cores = 2, memory_gb = 4, disk_size_gb = 2, labels = ["mini-swe-agent-plus-daniel"], total_timeout_minutes = 720, sandbox_client_max_workers = 128}
name = "mini-swe-agent-plus"

[env.log]
enabled = true
level = "debug"
vf_level = "debug"

[wandb]
project = "daniel-repro"
name = "repro-orch"

[log]
level = "debug"
